### ISSUE TITLE
I hope to fix some bugs urgently.

### ISSUE THREAD

**Issue by StarWC** [PFCraft/Mohist#10]
I use Google Translate,I hope you can understand.
After I turned on the server, I tested it back and forth in single-player mode and online mode, and confirmed that the problem was not from the MOD and plug-ins, so I guess it was a server-side bug.The following is a list of bugs I found:
1.mobs do not move
2.Being hurt will be repelled
3.A group of foods disappears once and only recovers the satiety of a single food.
4.There is a chance that the synthetic object will disappear on the body.
5.The amount of damage received is high
(Server version 0.0.4)

**Comment by Mgazul** [comment]
Ok, thanks for issues
