### ISSUE TITLE
[Mohist] Class not found

### ISSUE THREAD

**Issue by Flashback083** [PFCraft/Mohist#108]
Using build #386
I use Luckperm as Permission / group plugins, but this error appear too when server starting : 
https://gist.github.com/Flashback083/8e17d8a06b27c2bec71e48630bd0a361
(Version Mohist-1.1-cca9564-universal.jar worked)

Thanks !
~~plugins/itemnbtapi
https://gist.github.com/Flashback083/140a6a035b26e9bbb3c1484e4f561fa8~~
~~plugins/dungeonsxl-dist-0.18-SNAPSHOT-767.jar
https://gist.github.com/Flashback083/6adbff2e6e4893d384e5834a39fa4734~~

**Comment by Mgazul** [comment]
wepif.yml  setting 
resolvers:
  enabled:
    disabled:
      - GroupManagerResolver
