### ISSUE TITLE
[Plugin] VentureChat error loading

### ISSUE THREAD

**Issue by Flashback083** [PFCraft/Mohist#123]
**Version of Mohist :**
Mohist-1.2-bed4649

**Plugin link :**
https://www.spigotmc.org/resources/venturechat.771/

**Error :**
https://gist.github.com/Flashback083/341bc1439036f206eaf28ea038fe6971

Thanks !

**Comment by Mgazul** [comment]
I was using the latest build 403 and did not find this problem

**Comment by Mgazul** [comment]
Error rediscovered, waiting for fix

**Comment by Flashback083** [comment]
Seems fixed in latest
