### ISSUE TITLE
[Plugin] ChatControl - InvalidPluginException

### ISSUE THREAD

**Issue by Flashback083** [PFCraft/Mohist#132]
**Mohist version :**
Mohist-1.2-1f85d8e

**Link of the plugin :**
https://www.spigotmc.org/resources/chatcontrol-pro.10258/
Version free here : https://www.spigotmc.org/resources/chatcontrol%E2%84%A2-the-ultimate-chat-plugin-500-000-downloads-1-2-5-1-14-2.271/

**Issue :**
The plugin wont load

**Log :**
https://gist.github.com/Flashback083/11117dec86ba2f5ed96afc6e36df49b7

**Tested on a spigot 1.12.2 server ?**
Yes and it works

Hope it can be fixed soon ! Thanks for your work !

**Comment by Mgazul** [comment]
Fixed
