### ISSUE TITLE
在使用velocity进行跨服时，开启正版 无法显示其他玩家的正版皮肤。

### ISSUE THREAD

**Issue by qq839295616** [PFCraft/Mohist#134]
此问题我在velocity那边也反映过。
本来以为我velocity的问题，因为使用hexacord能正常使用。
后来velocity作者回复Spigot 和 Paper还有 SpongeForge 都能显示，可能是这边的问题，后来我也测试了一遍，也是如此，希望能解决下该问题。毕竟velocity对模组服之间的跨服友善了，不像其他。
下面是我向velocity那边反映的结果
VelocityPowered/Velocity#205

**Comment by a1640727878** [comment]
你可以试试用这个 https://forums.velocitypowered.com/t/simpleskins-restore-skins-for-offline-mode-servers/101 应急一下
