### ISSUE TITLE
[1.12.2]server constantly stalls with unknow reason

### ISSUE THREAD

**Issue by tmvkrpxl0** [PFCraft/Mohist#142]
I don't know why server is stalled
AFAIK, this happens randomly
Plugins: Some EssentialsX plugins, MultiWorld, lagg clear, DirectPortals, Luckperms, Trigger Reactor, LagMonitor, Clearlag
Mods: https://del.dog/tetiqafola.m
those are stall reports
```
https://del.dog/omolaleyif.nginx
https://del.dog/casirisehe.nginx
https://del.dog/vejixivohe.nginx
https://del.dog/botuqukope.nginx
https://del.dog/hazuwehiqa.nginx
```

**Comment by Mgazul** [comment]
Generate performance reports using Spark

**Comment by tmvkrpxl0** [comment]
I'm sorry to say this, but i already gave up fixing this issue
because the server that i was in developer team closed down forever
