### ISSUE TITLE
Crash on Mohist-5c53f01-server

### ISSUE THREAD

**Issue by ryan1161** [PFCraft/Mohist#163]
[Logs.zip](https://github.com/PFCraft/Mohist/files/3461600/Logs.zip)
Crashing on fresh install I have tried grabbing forge libraries directly from forge and also grabbing a lower version and server but looks like the sources are down for some of the libraries files.
I will attach a screenshot with my installer log and server crash log.

Start bat java -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms4G -Xmx6G -XX:hashCode=5 -jar Mohist-5c53f01-server.jar

**Comment by Mgazul** [comment]
Remove the old library files and start Mohsit, which automatically retrieves and decompresses the required libraries. The installer is obsolete and no longer useful

**Comment by ryan1161** [comment]
Thank you I tried to find anything about that installer but there wasn't much just found it and tried to see if I could get it to run. Thanks for the help love paper/forge this is going to be awesome so much more performer fixes with paper.
