### ISSUE TITLE
Crashing with mods v5c53f01

### ISSUE THREAD

**Issue by ryan1161** [PFCraft/Mohist#164]
I know that the server runs fine with the forge server jar.

Version of Server jar - 5c53f01 I can't tell what mod is crashing the server I will remove it cause it's totally worth having this type of server just need another set of eyes.

[logs.zip](https://github.com/PFCraft/Mohist/files/3461719/logs.zip)

**Comment by Mgazul** [comment]
teamwizardry mods

**Comment by ryan1161** [comment]
May I ask where in the logs did you see that linking to teamwizardry?

**Comment by Mgazul** [comment]
The first or more lines of the [main/ERROR]: log appear

**Comment by ryan1161** [comment]
Thank you I reported the problem to teamwizardry hopefully they will fix if not I guess I have to find another magic mod.

**Comment by Shwiiz** [comment]
electroblobs wizardry is a magic mod and working good
