### ISSUE TITLE
Tileentities ticktime limiting

### ISSUE THREAD

**Issue by nahlavnik** [PFCraft/Mohist#166]
Hey, is there any posibility that you will introduce tile entity tick interval feature? It's useful at 1.7.10 server running KCauldron (tileentities.yml) when there are many lagging tiles.

**Comment by Mgazul** [comment]
I'll try to add it when I know the details

**Comment by nahlavnik** [comment]
Here is example at Thermos (https://github.com/CyberdyneCC/Thermos/blob/bae97f16f0fac984a56083769ef75cb8a8eb1812/src/main/java/net/minecraftforge/cauldron/CauldronHooks.java) at canTileEntityTick method. Configuration example:
`net-minecraft-tileentity-TileEntityHopper:
tick-no-players: false # do not tick tile if there is no player near - it was too at KCauldron
tick-interval: 5 # do tile tick every 5 world ticks`

What resuls with:
`if world.getTime % 5 == 0 then
doTick()`

Main goal is to have config file with all tile entity types (at KCauldron it was updated every server run) and tick interval specified.

**Comment by Zilacon** [comment]
Theres a entities.yml version of this as well for mobs/players/animals

**Comment by Mgazul** [comment]
The upcoming
