### ISSUE TITLE
Error and not showing titlebar

### ISSUE THREAD

**Issue by SparkGNRK** [PFCraft/Mohist#17]
When I use Ultrapermissions and want to create a group or change chat format, the titlebar don't show and the console is spam of error. (sorry for my bad english)
[error.log](https://github.com/PFCraft/Mohist/files/3195049/error.log)

**Comment by Mgazul** [comment]
java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.PacketPlayOutTitle
The plugin uses nms and is temporarily unavailable!

**Comment by SparkGNRK** [comment]
oh ok thanks for your answer, did you know when we can use plugin using nms ?
