### ISSUE TITLE
UUID problem

### ISSUE THREAD

**Issue by Cronosus** [PFCraft/Mohist#19]
when i switched server to Offline, even "original" players gets wrong UUIDs, (i think from names), it causes they not get skins and also some inventory problems and model glitches

**Comment by SparkGNRK** [comment]
I thinks it's not a bug, when a server is in online mode player don't have the same UUID than the offline mode, so the player don't have the same 'data' (i think) in offline and online mode. In offline mode player can't have skins (but you can use the plugin skinsrestorer).

**Comment by Cronosus** [comment]
when our server was on 1.7.10 with bukkit+forge (cauldron) then players normally get uuid as online players if there were "original", if not, then it give them uuid from name

**Comment by Mgazul** [comment]
Need more information

**Comment by Cronosus** [comment]
dont know what else i can give, i tried even without mods and plugins with same results

**Comment by Mgazul** [comment]
What you said: inventory problems and model glitches
Is there a specific description or error message?

**Comment by Cronosus** [comment]
nope, its connected with mods, then nothing you can help, but its caused by this uuid change, because its set for original players and it glitched if they not get correct uuid
