### ISSUE TITLE
possible bukkit problem

### ISSUE THREAD

**Issue by Cronosus** [PFCraft/Mohist#22]
just refering to what contributor of Forestry says
https://github.com/ForestryMC/ForestryMC/issues/2412

**Comment by lliioollcn** [comment]
Lol, your report is not Mohist's

**Comment by Mgazul** [comment]
Need to update information: What are you doing before the crash?

**Comment by Cronosus** [comment]
it happened on tree farm, for a while it work, but after played relog, it keep crashing everytime he lo into game or when someone get close to this farm
