### ISSUE TITLE
IllegalStateException: Asynchronous Async Player Chunk Add! (Astralsorcery)

### ISSUE THREAD

**Issue by BlayzerQ** [PFCraft/Mohist#36]
https://gist.github.com/BlayzerQ/e1c813e12f95cee231aa5a5c75b3d993

**Comment by Mgazul** [comment]
You are using the old version, this issue has been fixed in the new version

**Comment by BlayzerQ** [comment]
I`m updated mod to astralsorcery-1.12.2-1.10.19, problem has still
https://gist.github.com/BlayzerQ/3d05894028513e0ac913d6e23e26f27f

**Comment by BlayzerQ** [comment]
Mohist-0.0.9-5497823-universal - this is not last version? (i`am use this)

**Comment by BlayzerQ** [comment]
Full server log:
[latest.log](https://github.com/PFCraft/Mohist/files/3296367/latest.log)
