### ISSUE TITLE
Huge bug with chat and player list

### ISSUE THREAD

**Issue by GDVE** [PFCraft/Mohist#37]
![image](https://user-images.githubusercontent.com/19783608/59593883-71af0f80-90fb-11e9-9eec-8ded294d3636.png)

After updating to Monist 1.0, I noticed such a bug.
Players are simply not visible if, via the Essentials plugin, you register the / list command in the chat. Also, messages are not sent to the chat, or rather, they are sent, but the rest of the players are not visible.

**Comment by GDVE** [comment]
Build #181 - does not have this bug

**Comment by Mgazul** [comment]
Occurs at 183?

**Comment by BlayzerQ** [comment]
I can confirm. When i call command /list, server say "0 players", but players are 15.
Also "/m" or "/msg" say "Player not found"

**Comment by BlayzerQ** [comment]
183 build is broken on jenkins, download not possible

**Comment by Mgazul** [comment]
Is the /list used in the console normal?

184

**Comment by BlayzerQ** [comment]
When /list used in the console - same. On 184 build - same.
