### ISSUE TITLE
A problem occurred running the Server launcher & libs download

### ISSUE THREAD

**Issue by BlayzerQ** [PFCraft/Mohist#38]
Last version from https://ci.codemc.org/job/PFCraft/job/Mohist/
On run with old libs Mohist-1.0-49df8a7-universal:
[net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:81]: A problem occurred running the Server launcher.
https://gist.github.com/BlayzerQ/288ee0c9ac6076c4d5ce234dbab19377

On installing with Mohist-1.0-49df8a7-installer:
FileNotFoundException: http://files.minecraftforge.net/maven/com/alibaba/fastjson/1.2.58/fastjson-1.2.58.jar
FileNotFoundException: http://files.minecraftforge.net/maven/com/maxqia/ReflectionRemapper/0.3-SNAPSHOT/ReflectionRemapper-0.3-SNAPSHOT.jar
FileNotFoundException: http://files.minecraftforge.net/maven/net/md-5/bungeecord-chat/1.12-SNAPSHOT/bungeecord-chat-1.12-SNAPSHOT.jar
FileNotFoundException: http://files.minecraftforge.net/maven/net/md-5/SpecialSource/1.8.5/SpecialSource-1.8.5.jar
FileNotFoundException: http://files.minecraftforge.net/maven/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
FileNotFoundException: http://files.minecraftforge.net/maven/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
FileNotFoundException: http://files.minecraftforge.net/maven/org/xerial/sqlite-jdbc/3.21.0.1/sqlite-jdbc-3.21.0.1.jar
FileNotFoundException: http://files.minecraftforge.net/maven/mysql/mysql-connector-java/5.1.46/mysql-connector-java-5.1.46.jar
FileNotFoundException: http://files.minecraftforge.net/maven/org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar
FileNotFoundException: http://files.minecraftforge.net/maven/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar

**Comment by Mgazul** [comment]
There is an error in the installer, delete the old library file and start Mohist, it will download the library file by itself.

**Comment by BlayzerQ** [comment]
Its work! Thx!
