### ISSUE TITLE
EntityLiving.setAttackTarget (null)

### ISSUE THREAD

**Issue by BlayzerQ** [PFCraft/Mohist#39]
https://gist.github.com/BlayzerQ/74efa1f3bce4a2c5c6581bb9bf157e44

**Comment by Mgazul** [comment]
This is just a warning, don't worry too much, thanks for feedback!

**Comment by BlayzerQ** [comment]
This warning creates frequent flooding in the console.

**Comment by Mgazul** [comment]
fixed
