### ISSUE TITLE
Bukkit Material enum

### ISSUE THREAD

**Issue by GMatrixGames** [PFCraft/Mohist#4]
Yo, I had seen a bit ago that you had a system that added forge items to the Bukkit material enum. I can't seem to find it again, is there a way I could get a commit link?

**Comment by Mgazul** [comment]
I probably forgot, I need to sort it out.

**Comment by GMatrixGames** [comment]
Ok, thanks. It would just be useful so Bukkit plugins can interface with modded items.

**Comment by GMatrixGames** [comment]
Also, if you have a discord, can you send it here. I'd like to talk about a few things.

**Comment by Mgazul** [comment]
https://discord.gg/HNmmrCV
