### ISSUE TITLE
New bug with terminal

### ISSUE THREAD

**Issue by GDVE** [PFCraft/Mohist#41]
With each new message in the console, the command I enter as if disappears.

![image](https://user-images.githubusercontent.com/19783608/59859713-f1e8a580-9385-11e9-86a7-e5322f12f24c.png)

**Comment by GDVE** [comment]
I tried to enter long commands and they disappeared. System: Ubuntu 18.04.2 LTS

**Comment by GDVE** [comment]
![image](https://user-images.githubusercontent.com/19783608/59860002-7fc49080-9386-11e9-9009-5eb3c3611a3a.png)

On version Monist 1.0

**Comment by Mgazul** [comment]
Have you tried the latest build? I don't have Ubuntu, I can't test it.

**Comment by GDVE** [comment]
![image](https://user-images.githubusercontent.com/19783608/59963014-dc928900-94f5-11e9-8a5d-5ed4353fcc38.png)
Testing last build

**Comment by Mgazul** [comment]
fiexd
