### ISSUE TITLE
hello author

### ISSUE THREAD

**Issue by LXSN** [PFCraft/Mohist#6]
it cannot download bungeecord-chat-1.12-SNAPSHOT and File not found in installer archive: /maven/co/aikar/fastutil-lite/1.0/fastutil-lite-1.0.jar
so can you fix it

**Comment by Mgazul** [comment]
The installer can't download non-forge lib, I have released a libraries.zip that contains everything you need.

**Comment by LXSN** [comment]
> The installer can't download non-forge lib, I have released a libraries.zip that contains everything you need.

oh thank I hope it can add multithreading

**Comment by Mgazul** [comment]
> > The installer can't download non-forge lib, I have released a libraries.zip that contains everything you need.
> 
> oh thank I hope it can add multithreading

Multithreading? Can only be added according to actual needs
