### ISSUE TITLE
Bad native

### ISSUE THREAD

**Issue by CKATEPTb** [PFCraft/Mohist#66]
native curve on remap reflection
![image](https://user-images.githubusercontent.com/33106029/60492641-13199200-9cb4-11e9-8728-6569d64a3bed.png)
www.github.com/projectkorra/projectkorra
tested on build #3​28.
Build #329 brocken
![image](https://user-images.githubusercontent.com/33106029/60492795-5bd14b00-9cb4-11e9-87dc-70f86e2aaeba.png)

**Comment by Mgazul** [comment]
Not all versions are available
