### ISSUE TITLE
Server keeps failing to launch

### ISSUE THREAD

**Issue by megoesrawr** [PFCraft/Mohist#8]
Error at launch: https://pastebin.com/ZZzuNCFa <-- new error

**Comment by megoesrawr** [comment]
also Galacticraft errors on load.
error: https://pastebin.com/AP7gphYb

**Comment by megoesrawr** [comment]
![image](https://user-images.githubusercontent.com/7830406/55100120-7b464f80-5097-11e9-85b6-22ff56232d3e.png)
Also forge 2823 is bugged so i dont know if you wanna use it yet.

**Comment by megoesrawr** [comment]
Still not working with Galacticraft :/ https://pastebin.com/SKvN0SSr

**Comment by Mgazul** [comment]
already fixed
