### ISSUE TITLE
CPU usage 100-200% with NO MODS or PLUGINS 200-560% with mods/plugins. [HIGH PRIORITY]

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#83]
Im using the Tekxit modpack, when using 0.0.9 its using around 80-120% cpu. When using 1.2 its using 200-560% cpu.

Why such a massive jump in cpu usage? Is there a setting thats doing this? If so how do i nuke it?

**Comment by Zilacon** [comment]
So its not the modpack, its mohist itself.
I literally ram Mohist with NO plugins and NO mods and it is pinned at 120-200% cpu usage.

Can there be a fix for thid?

**Comment by Zilacon** [comment]
So its not the modpack, its mohist itself.
I literally ram Mohist with NO plugins and NO mods and it is pinned at 120-200% cpu usage.

Can there be a fix for this?
@Mgazul @azbh111

**Comment by Zilacon** [comment]
Apparently server thread 12 and world mapping is causing the cpu usage.
![Screenshot_253](https://user-images.githubusercontent.com/3002248/60644349-b240a580-9dea-11e9-986f-25d5c53adc5d.png)

**Comment by azbh111** [comment]
#85 
One of the fixes

**Comment by azbh111** [comment]
Now cop usage only 1% with no mods and plugins.

**Comment by azbh111** [comment]
Do you know which mod or plugin “Background world mapping” thread belong to?
Or can you give me your serverpack, then I can test on it.

**Comment by Zilacon** [comment]
Apparently Thread 12 is the sleep thread on Mohist.
Background world mapping seems to be Galacticraft.
