### ISSUE TITLE
LiteBans error

### ISSUE THREAD

**Issue by CKATEPTb** [PFCraft/Mohist#86]
![image](https://user-images.githubusercontent.com/33106029/60673827-61c85700-9e81-11e9-82ff-d099f621a82b.png)
https://www.spigotmc.org/resources/litebans.3715/

**Comment by azbh111** [comment]
Should be fixed in #78

**Comment by CKATEPTb** [comment]
> Should be fixed in #78

No

**Comment by azbh111** [comment]
#95 fixed it
