### ISSUE TITLE
Unable to join server on Build #358 (Server locks up on start, process needs to be killed)

### ISSUE THREAD

**Issue by Zilacon** [PFCraft/Mohist#94]
Attempting to join the server just times out entirely. The server does recognize a connection is being made and shows the UUID but it does not even show my username, ip, or anything else.

**Comment by Mgazul** [comment]
I don't have this problem and need more information

**Comment by Zilacon** [comment]
I literally have nothing to give for information. All it shows is a UUID. The server also refuses to shutdown on that version, i have to kill the process.

Im currently using an older version which works just fine.

**Comment by Zilacon** [comment]
Can confirm this issue is present on OpenJDK and OpenJ9.

**Comment by Zilacon** [comment]
@azbh111 So i removed all mods and plugins (which arent a problem on #346) and the server does start and is responsive stand alone on OpenJ9.

Using the Tekxit modpack with latest version will cause a perma deadlock, no console commands will work. Cannot join, cannot shutdown. Switching to #346 everything works fine again besides the other errors with compatibility ive been posting. But with #346 you can join, use plugins, commands, and stop the server.

I dont know how to give you anymore information then that. And i have no idea what jstack is.

**Comment by Zilacon** [comment]
@azbh111 @Mgazul 
[debug-1.log](https://github.com/PFCraft/Mohist/files/3364402/debug-1.log)
[2019-07-06-1.log](https://github.com/PFCraft/Mohist/files/3364403/2019-07-06-1.log)

**Comment by azbh111** [comment]
There may be a deadlock. see #98 
I temporarily removed the lock.

**Comment by Zilacon** [comment]
@azbh111 Can confirm latest version does not have this issue anymore.
But holograms still do not work >_>
